// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkt2bus.proto

package pb;

public final class Pkt2Bus {
    private Pkt2Bus() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface PacketOrBuilder extends
            // @@protoc_insertion_point(interface_extends:pb.Packet)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .pb.Packet.Type type = 1;</code>
         */
        int getTypeValue();
        /**
         * <code>optional .pb.Packet.Type type = 1;</code>
         */
        pb.Pkt2Bus.Packet.Type getType();

        /**
         * <code>optional bytes origin = 2;</code>
         */
        com.google.protobuf.ByteString getOrigin();

        /**
         * <code>optional int64 timestamp = 3;</code>
         */
        long getTimestamp();

        /**
         * <code>optional bytes payload = 4;</code>
         */
        com.google.protobuf.ByteString getPayload();
    }
    /**
     * Protobuf type {@code pb.Packet}
     */
    public  static final class Packet extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:pb.Packet)
            PacketOrBuilder {
        // Use Packet.newBuilder() to construct.
        private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Packet() {
            type_ = 0;
            origin_ = com.google.protobuf.ByteString.EMPTY;
            timestamp_ = 0L;
            payload_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private Packet(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();

                            type_ = rawValue;
                            break;
                        }
                        case 18: {

                            origin_ = input.readBytes();
                            break;
                        }
                        case 24: {

                            timestamp_ = input.readInt64();
                            break;
                        }
                        case 34: {

                            payload_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return pb.Pkt2Bus.internal_static_pb_Packet_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return pb.Pkt2Bus.internal_static_pb_Packet_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            pb.Pkt2Bus.Packet.class, pb.Pkt2Bus.Packet.Builder.class);
        }

        /**
         * Protobuf enum {@code pb.Packet.Type}
         */
        public enum Type
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>SYSLOG = 0;</code>
             */
            SYSLOG(0),
            /**
             * <code>SNMP_TRAP = 1;</code>
             */
            SNMP_TRAP(1),
            /**
             * <code>NETFLOW = 3;</code>
             */
            NETFLOW(3),
            /**
             * <code>SFLOW = 4;</code>
             */
            SFLOW(4),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>SYSLOG = 0;</code>
             */
            public static final int SYSLOG_VALUE = 0;
            /**
             * <code>SNMP_TRAP = 1;</code>
             */
            public static final int SNMP_TRAP_VALUE = 1;
            /**
             * <code>NETFLOW = 3;</code>
             */
            public static final int NETFLOW_VALUE = 3;
            /**
             * <code>SFLOW = 4;</code>
             */
            public static final int SFLOW_VALUE = 4;


            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Type valueOf(int value) {
                return forNumber(value);
            }

            public static Type forNumber(int value) {
                switch (value) {
                    case 0: return SYSLOG;
                    case 1: return SNMP_TRAP;
                    case 3: return NETFLOW;
                    case 4: return SFLOW;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Type> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                        public Type findValueByNumber(int number) {
                            return Type.forNumber(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return pb.Pkt2Bus.Packet.getDescriptor().getEnumTypes().get(0);
            }

            private static final Type[] VALUES = values();

            public static Type valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private Type(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:pb.Packet.Type)
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;
        /**
         * <code>optional .pb.Packet.Type type = 1;</code>
         */
        public int getTypeValue() {
            return type_;
        }
        /**
         * <code>optional .pb.Packet.Type type = 1;</code>
         */
        public pb.Pkt2Bus.Packet.Type getType() {
            pb.Pkt2Bus.Packet.Type result = pb.Pkt2Bus.Packet.Type.valueOf(type_);
            return result == null ? pb.Pkt2Bus.Packet.Type.UNRECOGNIZED : result;
        }

        public static final int ORIGIN_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString origin_;
        /**
         * <code>optional bytes origin = 2;</code>
         */
        public com.google.protobuf.ByteString getOrigin() {
            return origin_;
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 3;
        private long timestamp_;
        /**
         * <code>optional int64 timestamp = 3;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        public static final int PAYLOAD_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString payload_;
        /**
         * <code>optional bytes payload = 4;</code>
         */
        public com.google.protobuf.ByteString getPayload() {
            return payload_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != pb.Pkt2Bus.Packet.Type.SYSLOG.getNumber()) {
                output.writeEnum(1, type_);
            }
            if (!origin_.isEmpty()) {
                output.writeBytes(2, origin_);
            }
            if (timestamp_ != 0L) {
                output.writeInt64(3, timestamp_);
            }
            if (!payload_.isEmpty()) {
                output.writeBytes(4, payload_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != pb.Pkt2Bus.Packet.Type.SYSLOG.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_);
            }
            if (!origin_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, origin_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, timestamp_);
            }
            if (!payload_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, payload_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof pb.Pkt2Bus.Packet)) {
                return super.equals(obj);
            }
            pb.Pkt2Bus.Packet other = (pb.Pkt2Bus.Packet) obj;

            boolean result = true;
            result = result && type_ == other.type_;
            result = result && getOrigin()
                    .equals(other.getOrigin());
            result = result && (getTimestamp()
                    == other.getTimestamp());
            result = result && getPayload()
                    .equals(other.getPayload());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
            hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
            hash = (53 * hash) + getOrigin().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
            hash = (53 * hash) + getPayload().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static pb.Pkt2Bus.Packet parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static pb.Pkt2Bus.Packet parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static pb.Pkt2Bus.Packet parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static pb.Pkt2Bus.Packet parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static pb.Pkt2Bus.Packet parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static pb.Pkt2Bus.Packet parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static pb.Pkt2Bus.Packet parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static pb.Pkt2Bus.Packet parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static pb.Pkt2Bus.Packet parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static pb.Pkt2Bus.Packet parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(pb.Pkt2Bus.Packet prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code pb.Packet}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:pb.Packet)
                pb.Pkt2Bus.PacketOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return pb.Pkt2Bus.internal_static_pb_Packet_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return pb.Pkt2Bus.internal_static_pb_Packet_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                pb.Pkt2Bus.Packet.class, pb.Pkt2Bus.Packet.Builder.class);
            }

            // Construct using pb.Pkt2Bus.Packet.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                type_ = 0;

                origin_ = com.google.protobuf.ByteString.EMPTY;

                timestamp_ = 0L;

                payload_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return pb.Pkt2Bus.internal_static_pb_Packet_descriptor;
            }

            public pb.Pkt2Bus.Packet getDefaultInstanceForType() {
                return pb.Pkt2Bus.Packet.getDefaultInstance();
            }

            public pb.Pkt2Bus.Packet build() {
                pb.Pkt2Bus.Packet result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public pb.Pkt2Bus.Packet buildPartial() {
                pb.Pkt2Bus.Packet result = new pb.Pkt2Bus.Packet(this);
                result.type_ = type_;
                result.origin_ = origin_;
                result.timestamp_ = timestamp_;
                result.payload_ = payload_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof pb.Pkt2Bus.Packet) {
                    return mergeFrom((pb.Pkt2Bus.Packet)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(pb.Pkt2Bus.Packet other) {
                if (other == pb.Pkt2Bus.Packet.getDefaultInstance()) return this;
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                if (other.getOrigin() != com.google.protobuf.ByteString.EMPTY) {
                    setOrigin(other.getOrigin());
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
                    setPayload(other.getPayload());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                pb.Pkt2Bus.Packet parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (pb.Pkt2Bus.Packet) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int type_ = 0;
            /**
             * <code>optional .pb.Packet.Type type = 1;</code>
             */
            public int getTypeValue() {
                return type_;
            }
            /**
             * <code>optional .pb.Packet.Type type = 1;</code>
             */
            public Builder setTypeValue(int value) {
                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional .pb.Packet.Type type = 1;</code>
             */
            public pb.Pkt2Bus.Packet.Type getType() {
                pb.Pkt2Bus.Packet.Type result = pb.Pkt2Bus.Packet.Type.valueOf(type_);
                return result == null ? pb.Pkt2Bus.Packet.Type.UNRECOGNIZED : result;
            }
            /**
             * <code>optional .pb.Packet.Type type = 1;</code>
             */
            public Builder setType(pb.Pkt2Bus.Packet.Type value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>optional .pb.Packet.Type type = 1;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString origin_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>optional bytes origin = 2;</code>
             */
            public com.google.protobuf.ByteString getOrigin() {
                return origin_;
            }
            /**
             * <code>optional bytes origin = 2;</code>
             */
            public Builder setOrigin(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                origin_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional bytes origin = 2;</code>
             */
            public Builder clearOrigin() {

                origin_ = getDefaultInstance().getOrigin();
                onChanged();
                return this;
            }

            private long timestamp_ ;
            /**
             * <code>optional int64 timestamp = 3;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }
            /**
             * <code>optional int64 timestamp = 3;</code>
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 timestamp = 3;</code>
             */
            public Builder clearTimestamp() {

                timestamp_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>optional bytes payload = 4;</code>
             */
            public com.google.protobuf.ByteString getPayload() {
                return payload_;
            }
            /**
             * <code>optional bytes payload = 4;</code>
             */
            public Builder setPayload(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                payload_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional bytes payload = 4;</code>
             */
            public Builder clearPayload() {

                payload_ = getDefaultInstance().getPayload();
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:pb.Packet)
        }

        // @@protoc_insertion_point(class_scope:pb.Packet)
        private static final pb.Pkt2Bus.Packet DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new pb.Pkt2Bus.Packet();
        }

        public static pb.Pkt2Bus.Packet getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Packet>
                PARSER = new com.google.protobuf.AbstractParser<Packet>() {
            public Packet parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Packet(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Packet> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Packet> getParserForType() {
            return PARSER;
        }

        public pb.Pkt2Bus.Packet getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_pb_Packet_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_pb_Packet_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rpkt2bus.proto\022\002pb\"\226\001\n\006Packet\022\035\n\004type\030\001" +
                        " \001(\0162\017.pb.Packet.Type\022\016\n\006origin\030\002 \001(\014\022\021\n" +
                        "\ttimestamp\030\003 \001(\003\022\017\n\007payload\030\004 \001(\014\"9\n\004Typ" +
                        "e\022\n\n\006SYSLOG\020\000\022\r\n\tSNMP_TRAP\020\001\022\013\n\007NETFLOW\020" +
                        "\003\022\t\n\005SFLOW\020\004b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_pb_Packet_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_pb_Packet_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_pb_Packet_descriptor,
                new java.lang.String[] { "Type", "Origin", "Timestamp", "Payload", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}